### ISSUE TITLE
Interval Tab - Elevation is wrong

### ISSUE THREAD

**Issue by rilling** [rilling/OpenTracks-Concordia#235]
**Describe the bug**
Interval Tab shows the wrong elevation per/interval - data is wrong. Elevation per interval should be only a few meters. See screen capture below.

![217359545-f8f5e9e4-61a5-429d-b01c-7228b4394b5c](https://user-images.githubusercontent.com/1248571/221328746-c946feb5-72e0-4c70-bd1d-24e37a062515.png)

To see the correct elevation is press "By Time" Tab on the top of the screen. You will see that there are only marginal elevation changes during the duration of the track. Noise from the elevation data should be removed.

**Comment by anmolchabbra** [comment]
Our group (g4) has started analyzing the issue.

**Comment by Driven2Develop** [comment]
this issue will be assigned to @anmolchabbra @YManasa13

**Comment by sahrawatvinay** [comment]
> this issue will be assigned to @anmolchabbra @YManasa13 and work will be tracked as part of the G4 branch

Hello @Driven2Develop, 
@sahrawatvinay and @zadfiya have been working on this issue along with other team members, so this will remain assigned to our group. unassigning you for now.
Thanks.

**Comment by Driven2Develop** [comment]
Hello @sahrawatvinay,

thanks for letting us know. In that case if your team is already working on the task please continue. If you need any assistance or have a subtask for our group (ui/intervals) please contact us. 

Iymen A.

**Comment by sahrawatvinay** [comment]
> Hello @sahrawatvinay,
> 
> thanks for letting us know. In that case if your team is already working on the task please continue. If you need any assistance or have a subtask for our group (ui/intervals) please contact us.
> 
> Iymen A.

Sure, Will let you guys know.

**Comment by anmolchabbra** [comment]
Hello @sahrawatvinay 
I have also worked on this issue, and as per my understanding have tried to resolve it as follow:

1) I have showed the difference between gain_m and loss_m for that interval to show elevation.
2) Rather than showing two text fields, I have created one text field to show the resulted elevation gain or loss.
3) And then Up and down arrow are shown on screen dynamically through the code, rather than being static icons.

I would commit this code on our group local branch which is G4, so you can review it, currently I was trying to test the build in my android phone, but it was not generating results of stats, So debugging on it, you can look for reference for the what I did and happy to collaborate with you guys if you need help in any functionality.

Thanks.

**Comment by sahrawatvinay** [comment]
We analyzed the code and the calculation for the elevation seems correct, looks like there is some ambiguity in the data due to which the elevation values seem wrong. 
While browsing more on the Internet, and in the issues in the main repo of OpenTracks, there was this similar type of issue
https://github.com/OpenTracksApp/OpenTracks/issues/1108
![image](https://user-images.githubusercontent.com/33993564/226235446-85eabe2f-e90f-443c-b8d8-544afeea720a.png)
There is a potential that this issue is due to the sensors of the phone, due to which there is inaccuracy in reading the values on some of the phones, as discussed in the above-mentioned issue.
https://github.com/OpenTracksApp/OpenTracks/blob/main/README_TESTED_SENSORS.md

**Comment by AntasJain** [comment]
I have written a solution for this issue and issue #4, being part of Group 20, I was looking for a solution in Sensors component but I deviced a solution in stats/TrackStatistics.java where I am putting value of totalGain and totalLoss as the highest value for the particular interval, I am going to commit the same as part of deliverable 3, here is the screenshot for the same solution's result:
![Screenshot_20230417_164630](https://user-images.githubusercontent.com/68066464/232617449-c24f1ae7-df43-42fe-b39f-6066e7674b6f.png)

**Comment by sahrawatvinay** [comment]
Closing issue
